### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by adamnewman913** [adamnewman913/Project1#4]
As a busy Kansas Citian, I want a way to know the weather and the best places so I can effectively plan my day.
BackEnd Goals
- [ ]A searchable weather API/based on location

- [ ] GoogleMap that shows up on location/searchable

- [ ] Search bar showing key words (best local things)

- [ ]  Search term as a variable in JS file
FrontEnd Goals

- [ ] Functional links to other pages 

- [ ] Aesthetically pleasing UI

- [ ] Properly labeled divs to drop the API stuff

**Comment by ginkaku67** [comment]
fixed
